const DB_NAME='2nc-authority-db',DB_VERSION=1;let db;let MUSIC_DATA=[],COMIC_DATA=[];
const state={mode:'vinyl',selected:null,queue:JSON.parse(localStorage.getItem('2ncQueue')||'[]'),query:'',level:'',managerDataset:'music',managerSelected:null};
const profiles={vinyl:{title:'Vinyl Dividers',sub:'Search the internal Music Authority',dim:'5 × 0.675 in'},cd:{title:'CD Dividers',sub:'Search the internal Music Authority',dim:'2 × 0.675 in'},comic:{title:'Comic Dividers',sub:'Search the internal Comic Authority',dim:'3.5 × 0.675 in'},instrument:{title:'Instrument Tags',sub:'Create 4 × 6 retail instrument tags',dim:'6 × 4 in'},manager:{title:'Authority Manager',sub:'Add, edit, retire, import, and back up authority data',dim:'Internal database'}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const escapeHtml=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=e=>{const d=e.target.result;['music','comic'].forEach(n=>{if(!d.objectStoreNames.contains(n)){const s=d.createObjectStore(n,{keyPath:'id'});s.createIndex('status','status');s.createIndex('display','display')}})};req.onsuccess=()=>{db=req.result;resolve()};req.onerror=()=>reject(req.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function getAll(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function seed(){for(const kind of ['music','comic']){const existing=await getAll(kind);if(existing.length)continue;const rows=await fetch(`data/${kind==='music'?'music':'comics'}.json`).then(r=>r.json());const t=db.transaction(kind,'readwrite'),s=t.objectStore(kind);rows.forEach(r=>s.put({...r,status:'active',notes:r.notes||'',updatedAt:new Date().toISOString()}));await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)})}}
async function refreshData(){MUSIC_DATA=(await getAll('music')).filter(r=>r.status!=='retired');COMIC_DATA=(await getAll('comic')).filter(r=>r.status!=='retired');if(state.mode!=='manager'){renderResults();renderPreview()}renderManager()}
function cleanSeries(parent,series){let s=(series||'').trim();if(!parent)return s;const esc=parent.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');s=s.replace(new RegExp('^'+esc+'\\s*[:\\-–—]?\\s*','i'),'');return s||series}
function currentData(){return state.mode==='comic'?COMIC_DATA:MUSIC_DATA}function matches(r){const q=state.query.toLowerCase();const hay=state.mode==='comic'?[r.display,r.parent,r.series,r.publisher,r.type].join(' '):[r.name,r.display,r.genre,r.subgenre,r.type].join(' ');return(!q||hay.toLowerCase().includes(q))&&(!state.level||r.level===state.level)}
function resultName(r){return state.mode==='comic'?(r.primary?r.display:cleanSeries(r.parent,r.series)):r.name}function resultSub(r){return state.mode==='comic'?(r.primary?`${r.publisher||''} · Primary authority`:`${r.parent||'Standalone'} · ${r.publisher||''}`):[r.genre,r.subgenre,r.level].filter(Boolean).join(' · ')}
function renderResults(){if(['instrument','manager'].includes(state.mode))return;const all=currentData().filter(matches),rows=all.sort((a,b)=>(a.sort||resultName(a)).localeCompare(b.sort||resultName(b))).slice(0,400);$('#resultCount').textContent=`${rows.length}${all.length>400?'+':''} results`;$('#results').innerHTML=rows.map((r,i)=>`<div class="resultCard ${state.selected?.id===r.id?'selected':''}" data-i="${i}"><div><strong>${escapeHtml(resultName(r))}</strong><br><small>${escapeHtml(resultSub(r))}</small></div><span class="badge">${escapeHtml(r.level||r.type||'')}</span></div>`).join('')||'<div class="empty">No matching records</div>';$$('.resultCard').forEach(el=>el.onclick=()=>{state.selected=rows[+el.dataset.i];renderResults();renderPreview()})}
function renderPreview(){if(['instrument','manager'].includes(state.mode))return;const box=$('#labelPreview');if(!state.selected){box.className='label vinylLabel';box.innerHTML='<strong>Select a record</strong>';$('#addSelected').disabled=true;return}$('#addSelected').disabled=false;const r=state.selected;if(state.mode==='comic'){box.className='label comicLabel '+(r.primary?'primaryComic':'');box.innerHTML=r.primary?`<div class="series">${escapeHtml(r.display)}</div>`:`<div class="cue">${escapeHtml(r.parent)}</div><div class="series">${escapeHtml(cleanSeries(r.parent,r.series))}</div>`;$('#addHierarchy').classList.toggle('hidden',!r.parent&&!r.primary)}else{box.className='label '+(state.mode==='cd'?'cdLabel':'vinylLabel');box.innerHTML=`<strong>${escapeHtml(r.name)}</strong>`;$('#addHierarchy').classList.add('hidden')}$('#selectedDetails').textContent=resultSub(r)}
function queueRecord(r){return state.mode==='comic'?{uid:crypto.randomUUID(),mode:'comic',primary:r.primary,parent:r.parent||'',series:r.primary?r.display:cleanSeries(r.parent,r.series),name:r.display}:{uid:crypto.randomUUID(),mode:state.mode,name:r.name}}
function addSelected(){if(state.selected){state.queue.push(queueRecord(state.selected));saveQueue()}}function addAll(){currentData().filter(matches).slice(0,400).forEach(r=>state.queue.push(queueRecord(r)));saveQueue()}function addHierarchy(){const r=state.selected;if(!r)return;const p=r.primary?r.display:r.parent;COMIC_DATA.filter(x=>(x.primary&&x.display===p)||(!x.primary&&x.parent===p)).forEach(x=>state.queue.push(queueRecord(x)));saveQueue()}
function saveQueue(){localStorage.setItem('2ncQueue',JSON.stringify(state.queue));renderQueue()}function renderQueue(){$('#queuePill').textContent=`${state.queue.length} queued`;$('#queue').innerHTML=state.queue.map((r,i)=>`<div class="queueItem"><div><strong>${escapeHtml(r.mode==='comic'?(r.primary?r.name:r.series):r.mode==='instrument'?r.product:r.name)}</strong><br><small>${escapeHtml(r.mode==='comic'?(r.primary?'Primary authority':r.parent):r.mode==='instrument'?r.price:r.mode.toUpperCase())}</small></div><button data-i="${i}">×</button></div>`).join('')||'<div class="empty">Your print queue is empty.</div>';$$('.queueItem button').forEach(b=>b.onclick=()=>{state.queue.splice(+b.dataset.i,1);saveQueue()})}
function setMode(mode){state.mode=mode;state.selected=null;const p=profiles[mode];$('#pageTitle').textContent=p.title;$('#pageSub').textContent=p.sub;$('#dimensionText').textContent=p.dim;$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#searchPanel').classList.toggle('hidden',['instrument','manager'].includes(mode));$('.previewPanel').classList.toggle('hidden',['instrument','manager'].includes(mode));$('.queuePanel').classList.toggle('hidden',mode==='manager');$('#instrumentPanel').classList.toggle('hidden',mode!=='instrument');$('#managerPanel').classList.toggle('hidden',mode!=='manager');if(mode==='manager')renderManager();else{state.query='';$('#searchInput').value='';renderResults();renderPreview()}}
function printQueue(){if(!state.queue.length)return alert('Add at least one item to the print queue.');const groups={vinyl:[],cd:[],comic:[],instrument:[]};state.queue.forEach(r=>groups[r.mode].push(r));const w=window.open('','_blank');w.document.write(buildPrintDocument(groups));w.document.close();setTimeout(()=>w.print(),400)}
function buildPrintDocument(groups){let pages='';for(const[k,items]of Object.entries(groups)){if(!items.length)continue;const cfg={vinyl:[24],cd:[60],comic:[24],instrument:[2]}[k];for(let i=0;i<items.length;i+=cfg[0]){pages+=`<section class="sheet ${k}">`;items.slice(i,i+cfg[0]).forEach(r=>{if(k==='comic')pages+=`<div class="pl comic">${r.primary?`<b>${escapeHtml(r.name)}</b>`:`<small>${escapeHtml(r.parent)}</small><b>${escapeHtml(r.series)}</b>`}</div>`;else if(k==='instrument')pages+=`<div class="tag"><div class="orange"><span>${escapeHtml(r.price)}</span><em>2ND<br>& CHARLES</em></div><div class="prod">${escapeHtml(r.product).replace(/\n/g,'<br>')}</div><footer>2ndandcharles.com</footer></div>`;else pages+=`<div class="pl ${k}"><b>${escapeHtml(r.name)}</b></div>`});pages+='</section>'}}return `<!doctype html><style>@page{size:letter;margin:.25in}*{box-sizing:border-box}body{margin:0;font-family:Arial}.sheet{page-break-after:always;display:grid;align-content:start;justify-content:center}.sheet.vinyl{grid-template-columns:repeat(2,5in)}.sheet.cd{grid-template-columns:repeat(4,2in)}.sheet.comic{grid-template-columns:repeat(2,3.5in)}.sheet.instrument{grid-template-columns:6in;gap:.25in}.pl{height:.675in;border:1px dashed #aaa;display:flex;align-items:center;justify-content:center;text-align:center;padding:.04in;overflow:hidden}.pl.vinyl b{font-size:18pt}.pl.cd b{font-size:10pt}.pl.comic{flex-direction:column}.pl.comic small{font-size:7pt;color:#666}.pl.comic b{font-size:16pt}.tag{width:6in;height:4in;position:relative;overflow:hidden;border:1px dashed #aaa;color:#e38f65}.orange{position:absolute;left:0;top:0;width:2in;height:4in;border-radius:0 100% 100% 0;background:#e38f65;color:white}.orange span{position:absolute;font-size:42pt;transform:rotate(-90deg);left:-.2in;top:1.55in}.orange em{position:absolute;bottom:.15in;left:.15in;font-size:8pt;font-style:normal;font-weight:bold}.prod{position:absolute;left:2.1in;right:.2in;top:.25in;bottom:.5in;display:flex;align-items:center;justify-content:center;text-align:center;font-size:29pt;font-weight:bold}.tag footer{position:absolute;right:.15in;bottom:.12in;color:#555;font-size:7pt}</style>${pages}`}
function showModal(t,h){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=h;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
function customLabel(){if(state.mode==='instrument')return showInstrumentModal();const comic=state.mode==='comic';showModal('Create custom label',`<label>${comic?'Main authority':'Artist name'}<input id="customMain"></label>${comic?'<label>Series title<input id="customSub"></label>':''}<button id="saveCustom" class="primaryButton">Add to queue</button>`);$('#saveCustom').onclick=()=>{const m=$('#customMain').value.trim(),s=comic?$('#customSub').value.trim():'';if(!m)return;state.queue.push(comic?{uid:crypto.randomUUID(),mode:'comic',primary:!s,parent:s?m:'',series:s,name:m}:{uid:crypto.randomUUID(),mode:state.mode,name:m});saveQueue();closeModal()}}
function showInstrumentModal(){showModal('Create instrument tag','<label>Price<input id="mPrice"></label><label>Product name<textarea id="mProduct" rows="5"></textarea></label><button id="saveTag" class="primaryButton">Add to queue</button>');$('#saveTag').onclick=()=>{addTagValues($('#mPrice').value,$('#mProduct').value);closeModal()}}
function addTagValues(price,product){product=product.trim();if(!product)return;price=price.trim();if(price&&!price.startsWith('$'))price='$'+price;state.queue.push({uid:crypto.randomUUID(),mode:'instrument',price,product});saveQueue()}
function makeId(kind){const p=kind==='music'?'MUS':'COM';return `${p}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
async function renderManager(){if(!db||state.mode!=='manager')return;const kind=$('#managerDataset').value||state.managerDataset;state.managerDataset=kind;const q=($('#managerSearch').value||'').toLowerCase(),status=$('#managerStatus').value||'active';let rows=await getAll(kind);rows=rows.filter(r=>(status==='all'||(r.status||'active')===status)&&(!q||JSON.stringify(r).toLowerCase().includes(q))).sort((a,b)=>(a.sort||a.display||a.name||'').localeCompare(b.sort||b.display||b.name||''));$('#managerCount').textContent=`${rows.length} records`;$('#managerResults').innerHTML=rows.slice(0,700).map((r,i)=>`<div class="resultCard ${state.managerSelected?.id===r.id?'selected':''}" data-id="${escapeHtml(r.id)}"><div><strong>${escapeHtml(r.display||r.name)}</strong><br><small>${escapeHtml(kind==='comic'?[r.parent,r.series,r.publisher].filter(Boolean).join(' · '):[r.genre,r.subgenre,r.type].filter(Boolean).join(' · '))}</small><div class="recordFlags"><span class="flag">${escapeHtml(r.level||'')}</span>${r.status==='retired'?'<span class="flag retired">Retired</span>':''}</div></div></div>`).join('')||'<div class="empty">No records</div>';$$('#managerResults .resultCard').forEach(el=>el.onclick=()=>{state.managerSelected=rows.find(r=>r.id===el.dataset.id);fillEditor(state.managerSelected);renderManager()})}
function fillEditor(r){$('#editorEmpty').classList.add('hidden');$('#authorityForm').classList.remove('hidden');const comic=state.managerDataset==='comic';$('#parentField').classList.toggle('hidden',!comic);$('#seriesField').classList.toggle('hidden',!comic);$('#publisherField').classList.toggle('hidden',!comic);$('#genreField').classList.toggle('hidden',comic);$('#editId').value=r.id||'';$('#editDisplay').value=r.display||r.name||'';$('#editName').value=r.name||r.display||'';$('#editParent').value=r.parent||'';$('#editSeries').value=r.series||'';$('#editType').value=r.type||'';$('#editLevel').value=r.level||'Recommended';$('#editGenre').value=r.genre||'';$('#editPublisher').value=r.publisher||'';$('#editNotes').value=r.notes||'';$('#retireRecord').textContent=r.status==='retired'?'Restore':'Retire'}
function newAuthority(){state.managerSelected={id:'',status:'active'};fillEditor(state.managerSelected)}
async function saveAuthority(e){e.preventDefault();const kind=state.managerDataset,comic=kind==='comic';const old=state.managerSelected||{};const display=$('#editDisplay').value.trim();if(!display)return;const obj={...old,id:$('#editId').value||makeId(kind),display,name:$('#editName').value.trim()||display,type:$('#editType').value.trim(),level:$('#editLevel').value,status:old.status||'active',notes:$('#editNotes').value.trim(),updatedAt:new Date().toISOString()};if(comic){obj.parent=$('#editParent').value.trim();obj.series=$('#editSeries').value.trim();obj.publisher=$('#editPublisher').value.trim();obj.primary=!obj.series;obj.sort=obj.series||obj.display}else{obj.genre=$('#editGenre').value.trim();obj.sort=obj.display}await put(kind,obj);state.managerSelected=obj;await refreshData();alert('Authority saved.')}
async function toggleRetire(){if(!state.managerSelected?.id)return;state.managerSelected.status=state.managerSelected.status==='retired'?'active':'retired';await put(state.managerDataset,state.managerSelected);await refreshData();fillEditor(state.managerSelected)}
async function deleteSelected(){if(!state.managerSelected?.id||!confirm('Permanently delete this authority?'))return;await del(state.managerDataset,state.managerSelected.id);state.managerSelected=null;$('#authorityForm').classList.add('hidden');$('#editorEmpty').classList.remove('hidden');await refreshData()}
async function exportBackup(){const payload={schema:1,exportedAt:new Date().toISOString(),music:await getAll('music'),comic:await getAll('comic')};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download=`2NC_Authority_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(file){const payload=JSON.parse(await file.text());if(!payload.music||!payload.comic)throw Error('Not a valid 2NC backup');if(!confirm('Replace the internal Music and Comic databases with this backup?'))return;for(const kind of ['music','comic']){const t=db.transaction(kind,'readwrite'),s=t.objectStore(kind);s.clear();payload[kind].forEach(r=>s.put(r));await new Promise((res,rej)=>{t.oncomplete=res;t.onerror=()=>rej(t.error)})}await refreshData();alert('Backup imported.')}
function bind(){$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('#searchInput').oninput=e=>{state.query=e.target.value;renderResults()};$('#levelFilter').onchange=e=>{state.level=e.target.value;renderResults()};$('#clearSearch').onclick=()=>{$('#searchInput').value='';state.query='';renderResults()};$('#addSelected').onclick=addSelected;$('#addAll').onclick=addAll;$('#addHierarchy').onclick=addHierarchy;$('#clearQueue').onclick=()=>{state.queue=[];saveQueue()};$('#printBtn').onclick=printQueue;$('#customBtn').onclick=customLabel;$('#addTag').onclick=()=>addTagValues($('#priceInput').value,$('#productInput').value);$('#priceInput').oninput=e=>{$('.tagPrice').textContent=e.target.value?(e.target.value.startsWith('$')?e.target.value:'$'+e.target.value):'$239'};$('#productInput').oninput=e=>{$('.tagProduct').innerHTML=escapeHtml(e.target.value||'PRODUCT NAME').replace(/\n/g,'<br>')};$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#aboutBtn').onclick=()=>showModal('About','<p><strong>2NC Authority Suite v2.0</strong></p><p>The internal browser database is the source of truth. Excel is no longer required.</p>');$('#managerDataset').onchange=()=>{state.managerSelected=null;renderManager()};$('#managerSearch').oninput=renderManager;$('#managerStatus').onchange=renderManager;$('#newAuthority').onclick=newAuthority;$('#authorityForm').onsubmit=saveAuthority;$('#retireRecord').onclick=toggleRetire;$('#deleteRecord').onclick=deleteSelected;$('#exportBackup').onclick=exportBackup;$('#importBackup').onchange=e=>importBackup(e.target.files[0]).catch(err=>alert(err.message))}
(async()=>{await openDB();await seed();bind();await refreshData();renderQueue();setMode('vinyl');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js')})();